jobs:
- job: Test
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: NodeTool@0 
    inputs:
      versionSpec: '10.x'
  - script: |
      npm install
      npm run lint

- job: Publish
  pool:
    vmImage: 'ubuntu-16.04'
  dependsOn: Test
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
  - script: npm install
  - task: Npm@1
    inputs:
        command: publish
        publishRegistry: useExternalRegistry
        publishEndpoint: npmjs
