name: Quality Check

on:
  push:
    branches:
      - master
    pull_request:

jobs:
  qc:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v1
      - name: Install Package Dependencies
        run: yarn
      - name: Lint
        run: yarn run lint
